### ISSUE TITLE
Recruit Task 1

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/py-recruit#2]
# DoD ✅ 

- [x] The user is able to perform 4 basic operations: `+`/`-`/`*`/`/`
- [x] The user is doing the operations till the exit command is provided (f.eg. exit/quit etc.), once such a command would be provided, the app should stop
- [x] The user is able to check the calculation history (once the app is closed, the history is cleared i.e.: it's not saved in DB)

# Description ✉️ 

Create the `Calculator` app in the OOP style using the MVC pattern. The main loop should finish once the exit/quit command would be provided, psb:

```python
operation = ''
while operation != 'quit':
  # some operations
```

The inputs for the app are the following, all of them should be fetched from the user using the `input` function in each iteration of the loop:

- operation (`exit`, `+`, `-`, `*`, `/`),
- var1,
- var2.

Once the input data would be provided, based on the operation the app could perform the proper method (addition/subtraction/multiplication/division). The suggestion is to create the method for all of those operations (it could be handled in one block of code, but we'd like to show the OOP approach). 💪 🚀 

Good luck 🤞 .

All of the processes related to the GIT/Task workflow must be performed.

# Documentation 

## GIT commands 👨‍💻 

![Image](https://github.com/JaRutkowski/py-recruit/assets/26207880/ffa0a472-cd60-4941-891a-43d96cafb1f1)

## GIT branched 🌳 

![Image](https://github.com/JaRutkowski/py-recruit/assets/26207880/c0b2e76a-3278-4107-a193-55ff0fb44451)

## Task lifecycle 📦 

![Image](https://github.com/JaRutkowski/py-recruit/assets/26207880/8643d7a6-76f4-4d6c-92bc-fb0b8a29a0ca)

**Comment by jaroslawjalocha** [comment]
@JaRutkowski ready to review task
